// <auto-generated />
using System;
using LabFlow.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabFlow.API.Migrations
{
    [DbContext(typeof(FhirDbContext))]
    partial class FhirDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("LabFlow.API.Data.Entities.PatientEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FhirJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("GivenName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BirthDate")
                        .HasDatabaseName("IX_Patients_BirthDate");

                    b.HasIndex("FamilyName")
                        .HasDatabaseName("IX_Patients_FamilyName");

                    b.HasIndex("GivenName")
                        .HasDatabaseName("IX_Patients_GivenName");

                    b.HasIndex("Identifier")
                        .HasDatabaseName("IX_Patients_Identifier");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Patients_IsDeleted");

                    b.HasIndex("LastUpdated")
                        .HasDatabaseName("IX_Patients_LastUpdated");

                    b.ToTable("Patients", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
